---
jobs:
- name: job-upload-release
  public: true
  plan:
  - get: source-code
    params: { depth: 1 }
  - task: upload-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: starkandwayne/concourse}
      run:
        path: source-code/nginx_release/ci/tasks/upload-release-with-vars.sh
      params:
        BOSH_ENVIRONMENT: (( grab bosh.environment ))
        BOSH_CLIENT: (( grab bosh.client ))
        BOSH_CLIENT_SECRET: (( grab bosh.client_secret ))
        BOSH_DIRECTOR: (( grab bosh.director ))
        BOSH_DEPLOYMENT: (( grab bosh.deployment ))
        BOSH_CA_CERT: (( grab bosh.ca_cert ))
      inputs:
        - name: source-code
- name: job-deploy-release
  public: true
  plan:
  - get: source-code
    trigger: true
    passed: [job-upload-release]
    params: { depth: 1 }
  - task: deploy-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: starkandwayne/concourse}
      run:
        path: source-code/nginx_release/ci/tasks/deploy-release-with-vars.sh
      params:
        BOSH_ENVIRONMENT: (( grab bosh.environment ))
        BOSH_CLIENT: (( grab bosh.client ))
        BOSH_CLIENT_SECRET: (( grab bosh.client_secret ))
        BOSH_DIRECTOR: (( grab bosh.director ))
        BOSH_DEPLOYMENT: (( grab bosh.deployment ))
        BOSH_CA_CERT: (( grab bosh.ca_cert ))
      inputs:
        - name: source-code

resources:
- name: source-code
  type: git
  source:
    uri: (( grab github.repository ))
    branch: (( grab github.branch ))
